### ISSUE TITLE
create basic watch-tower

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#108]
## Scope
- list all ongoing exits and details:
  - tx hash of utxo in exit
  - tx hash of tx spending utxo (if any). That's one of the things we are watching for. Exits which have such tx should be marked as potentially invalid/requiring attention.
- for each color, compare total UTXO size with balance of plasma contract:
  - `plasma balance >= total UTXO value + exit sum` — valid chain
  - otherwise — chain is invalid. That's an invalid condition we are watching for as well
- display all that on status page.

## Deliverables
- a page with client-side scripts.

## Gain for the project
- ability to notice and slash invalid exits (basic monitoring)
- one-look health indicator with balances
- create a base for more complex watch towers

---

### Roles: 
bounty gardener: @johannbarbie  / 10% 
bounty worker: @StevenJNPearce / 80%
bounty reviewer: @johannbarbie  / 10%

**Comment by StevenJNPearce** [comment]
I would be happy to tackle this. Continuous deployment URL for my branch: https://practical-mahavira-503a54.netlify.com/

So far all there is to see is a table with the ongoing exits; I only just started working on it a few hours ago.

**Comment by StevenJNPearce** [comment]
> * for each color, compare total UTXO size with balance of plasma contract.

How do I get all the UTXOs? I didn't find any method exposed, only plasma_unspent which returns just for one address.

**Comment by StevenJNPearce** [comment]
> * tx hash of tx spending utxo (if any). That's one of the things we are watching for. Exits which have such tx should be marked as potentially invalid/requiring attention.

Am I missing a more elegant way to do this or does it need some sort of database/caching layer? I tried looping thru the transactions comparing the inputs with the txHash from the exit events and it took 10 minutes!

**Comment by johannbarbie** [comment]
> Am I missing a more elegant way to do this

i see 2 ways to do this:
a) add an index in the node database by prevOut/outpoint (spentTxHash + outputIndex).
b) make sure that every exit has a corresponding `exitTx` in the node db. exitTxns are deterministic, and it should be enough to query the node by it's hash. you can construct it from the exit data like [here](https://github.com/leapdao/leap-core/blob/f3feffee104d7ceb2d48384409b95a3215e8ca14/lib/transaction.spec.js#L33).

i think a) would require a separate bounty on the node side (any-one welcome to spec that). until we don't have that maybe b) is worth exploring.

**Comment by StevenJNPearce** [comment]
>> * `plasma balance >= total UTXO value + exit sum` — valid chain

@johannbarbie Here 'exit sum' is all not finalized exits from the plasma contract including those that may be invalid?

**Comment by johannbarbie** [comment]
> Here 'exit sum' is sum of all not finalized exits from the plasma contract including those that may be invalid, or sum of those that have exitTx in node db?

sry for the late response, was on a flight. that is a really good question 🤔 . i think all active exits that have a change to get finalized (and by that affect the bookkeeping of the chain), so that `!finalized && amount > 0`.

**Comment by StevenJNPearce** [comment]
> > Here 'exit sum' is sum of all not finalized exits from the plasma contract including those that may be invalid, or sum of those that have exitTx in node db?
> 
> sry for the late response, was on a flight. that is a really good question 🤔 . i think all active exits that have a change to get finalized (and by that affect the bookkeeping of the chain), so that `!finalized && amount > 0`.

I've implemented it like this, but thinking on it further maybe a 3 state 'traffic light' is better? i.e. Green - Chain is ok; Orange - There are bad open exits with a chance to get finalized. Red - Invalid exits were already finalized.

**Comment by StevenJNPearce** [comment]
@eezcjkr Have you had a chance to review this yet?

**Comment by eezcjkr** [comment]
@StevenJNPearce Hi Steven. Sorry for the delay. I will review this tomorrow (or in roughly 16 hours since I am not aware of your timezone). Been busy with random stuff past few days, I apologise for the wait.

**Comment by johannbarbie** [comment]
i can take the review over. on it now
