### ISSUE TITLE
firefox unbearable slow

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#111]
my version: 65.0b10 (64-bit)

**Comment by johannbarbie** [comment]
also wallet not working

**Comment by troggy** [comment]
what's the error?

**Comment by johannbarbie** [comment]
can't check, browser lags too much to open developer console.

**Comment by troggy** [comment]
addressed slowness in #117 and https://github.com/leapdao/bridge-ui/commit/cc3d3eeedabd402ee034e6d2ee7f359c8b5022de . Still not fast, but looks better

Addressed wallet issue in https://github.com/leapdao/bridge-ui/commit/291da697e402eb948f432e5ed4b21f88e0fe3127

**Comment by johannbarbie** [comment]
awesome. thx :)
