### ISSUE TITLE
bridge-ui loader spinning forever at block height 4223

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#115]
height 4223 according to RPC, error in browser console after few minutes:

<img width="527" alt="screen shot 2019-01-20 at 3 20 40 pm" src="https://user-images.githubusercontent.com/659301/51440406-033e6080-1cc7-11e9-92fc-bb32861265ca.png">

**Comment by eezcjkr** [comment]
have you tried flushing your local cache?

**Comment by eezcjkr** [comment]
Looks like we are filling it up too much

**Comment by troggy** [comment]
clear localStorage once when running the fixed version. I've disable blockchain downloading see #117
