### ISSUE TITLE
` no blocks contained` when clicking exit

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#123]
<img width="1049" alt="screen shot 2019-01-24 at 3 50 25 pm" src="https://user-images.githubusercontent.com/659301/51686017-d1dbd280-1fef-11e9-9e15-88cfe9cf6c5f.png">

**Comment by troggy** [comment]
reproduced right now. The input is consolidation tx

**Comment by troggy** [comment]
Affected UTXOs mined in the block on the period boundary (32, 64 and so on). Fixed in https://github.com/leapdao/leap-core/pull/59 via #129
