### ISSUE TITLE
balances missmatch

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#126]
<img width="549" alt="screen shot 2019-01-26 at 10 32 06 pm" src="https://user-images.githubusercontent.com/659301/51835199-efb17c00-22fc-11e9-8594-10b901d5cc42.png">

on delta testnet

**Comment by troggy** [comment]
which code is running at the node?

**Comment by johannbarbie** [comment]
with the https://github.com/leapdao/leap-node/tree/v3.1.5 release of node and contracts at https://github.com/leapdao/leap-contracts/tree/v0.1.1
as described here: https://leapdao.slack.com/archives/CFKUNHHC7/p1548489683001600

**Comment by troggy** [comment]
assuming it was a BigInt-transition glitch. Reopen when reproduced
