### ISSUE TITLE
actual value of transfer a few dozens of totter bigger

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#131]
E.g. Given a single UTXO 3.999999999999999935 transfer 0.999999999999999935 to myself (split)

Expected:
2 UTXOs: 0.999999999999999935 and 3

Actual:
2 UTXOs: 0.999999999999999872 and 3.000000000000000063

**Comment by troggy** [comment]
calcInputs seems off

**Comment by johannbarbie** [comment]
also true for main-net token. i had 55, deposited 2.2, got this:

<img width="266" alt="screen shot 2019-01-30 at 2 41 10 pm" src="https://user-images.githubusercontent.com/659301/51985031-27efc080-249d-11e9-88ec-5ea3d912c949.png">

**Comment by troggy** [comment]
yes, found an error in bridge in tokens → cents caluclations
