### ISSUE TITLE
Pending deposits stay displayed after being included in tendermint chain

### ISSUE THREAD

**Issue by eezcjkr** [leapdao/bridge-ui#141]
<img width="1396" alt="screenshot 2019-02-04 at 12 41 42" src="https://user-images.githubusercontent.com/41610198/52189204-796fc500-287a-11e9-8c73-a8677ba3972b.png">

**Comment by StevenJNPearce** [comment]
Oddly I couldn't consistently reproduce this; seemed to work sometimes but not at others. Cause could be this: https://github.com/leapdao/bridge-ui/blob/65b1c914bc5ab61b901dfa45ddbcf5a6b2c5603c/src/routes/wallet/deposit.tsx#L113 This line doesn't do anything; maturedDeposits is block scoped to the function so removing an element from it at the last line is redundant.

**Comment by sunify** [comment]
> This line doesn't do anything; maturedDeposits is block scoped to the function so removing an element from it at the last line is redundant.

It scoped to `for` loop block, not function

**Comment by StevenJNPearce** [comment]
> > This line doesn't do anything; maturedDeposits is block scoped to the function so removing an element from it at the last line is redundant.
> 
> It scoped to `for` loop block, not function

Right, not sure how I misread that.
