### ISSUE TITLE
improve responsive/mobile version

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#148]
- less paddings/margins
- probably make nav dropdown better

**Comment by StevenJNPearce** [comment]
Everything on explorer page is broken on mobile. It's probably too much information to show within the width of a mobile screen, I suggest horizontal scroll for that page.

**Comment by troggy** [comment]
yes, I think nobody kept mobile version in mind and this is sort of low priority now when we are limited in resources.

**Comment by troggy** [comment]
mostly addressed in #159 and #169 .
