### ISSUE TITLE
Icons aren't visible on testnet.leapdao.org

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#151]
Expected:
![image](https://user-images.githubusercontent.com/163447/52478967-1f436c80-2bb8-11e9-9f58-a4cec3674c1a.png)

Actual:
![image](https://user-images.githubusercontent.com/163447/52478956-1783c800-2bb8-11e9-8cd0-47ea9056c417.png)

**Comment by sunify** [comment]
You need to whitelist icons here https://github.com/leapdao/bridge-ui/blob/master/src/icons.js

**Comment by sunify** [comment]
Without this all icons (about 800Kb) will be included into bundle

**Comment by troggy** [comment]
@sunify awesome! Thanks for the tip 🙇‍♂️
