### ISSUE TITLE
slow exit failing transaction

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#176]
output is displayed as exitable (1.1 LEAP bottom right):

<img width="1135" alt="screen shot 2019-02-23 at 7 07 13 pm" src="https://user-images.githubusercontent.com/659301/53290076-81e35d80-379f-11e9-93ba-78c6a16c929f.png">

but fails on execution:
https://rinkeby.etherscan.io/tx/0x9b422fdf6f1a69fc82aff8468e5cc148dc97f9d33b393d3ddaf2bafe35580d68

**Comment by troggy** [comment]
not enough context to reproduce. My best bet is there was no period submitted for the UTXO in question or deposit exit weren't implemented yet
