### ISSUE TITLE
Announce migration and snapshot date n Bridge-UI

### ISSUE THREAD

**Issue by eshavkun** [leapdao/bridge-ui#194]
As part of migration to latest Tendermint version new mainnet will be built. This will includes suspension of deposits and exits on current mainnet and migrating UTXOs to a new mainnet. This bounty is about adding announcement of this with date of snapshop (after which no transaction will be taken into account) so users will be aware of this.

## Scope
- on the wallet page, show the message if deposits and exits are not enabled (both failing)
- message text "Network is undergoing maintenance. Deposits and exits are temporary disabled"
- disable "Deposit" and "Exit" buttons

## Deliveries
- updated bridge-ui code

## Purpose Alignment
- Make users aware of migration and suspension of current mainnet

## Bounty

gardener: | 15%
worker: @troggy | 65%
reviewer: | 20%

**Comment by troggy** [comment]
Needs link to blog post https://github.com/leapdao/leapdao-website/issues/89 once it ready

**Comment by troggy** [comment]
hm.. I don't think this will be needed much. Once exits and deposits are disabled we'd rather do migration right away (we don't want transfers to happen as well).

**Comment by eshavkun** [comment]
Yeah, you right! Looks correct
