### ISSUE TITLE
Dai rendered strange on register token page 

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/bridge-ui#195]
<img width="414" alt="screen_shot_2019-04-03_at_9 00 31_pm" src="https://user-images.githubusercontent.com/659301/55507762-ad881c00-5658-11e9-8911-66a56f7389f6.png">

**Comment by johannbarbie** [comment]
Wasn't me, saw this through screenshare on a call.

**Comment by troggy** [comment]
too old. feel free to reopen if reoccurs (ideally with steps to reproduce)
