### ISSUE TITLE
heartbeat display in bridge-ui

### ISSUE THREAD

**Issue by simonweniger** [leapdao/bridge-ui#259]
## Problem Description

- when a prospect validator submits the [registration request](https://docs.google.com/forms/d/e/1FAIpQLSdQtc5LoEyWkc5-86SOLW3xK8cRNwuByC7SIrA9MdWeAiuBZw/viewform) the testnet/mainnet commander will mint a heartbeat token, and send it to the address of the validator
- once the heartbeat token arrived, the validator will start spending it regularly
- the commander needs to be able to measure the uptime over a period of x hours/days, to be sure that the validator is set up well, before assigning a slot.

## Scope

- create a screen in bridge-ui that lists all slots (see git history, once existed)
- calculate and display uptime of slot based on heartbeat token spending

## Deliverables

- code
- tests

## Gain for the project

- unblock Ops circle, to unblock ECO system for validator launch

## Expert / Affected

affected: @troggy 
expert: @johannbarbie 

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: name / share
bounty reviewer: name / share

**Comment by troggy** [comment]
why it should be a part of bridge-ui? If it is just for commander it could be a CLI

**Comment by troggy** [comment]
@MaxStalker assigning this one to you, right?

by any chance, maybe you know the answer for the question above? :)

**Comment by MaxStalker** [comment]
@troggy Judging by the repo history, once there was a route, which helped to monitor validator slots. I believe, the ide was to excavate and enchance that code :)

**Comment by troggy** [comment]
I'm taking this over as per "Bounty takeover" policy. Reason: nothing happens for almost 2 months and the bounty is on the roadmap.

Shout with objections please

**Comment by troggy** [comment]
"uptime" still not defined in this bounty, so I just ignored it
