### ISSUE TITLE
create a IPFS storage solution for the governance proposals

### ISSUE THREAD

**Issue by cyan-one** [leapdao/bridge-ui#270]
## Scope

- store the proposal titles and descirption on IPFS
- make sure the data is pinned  

## Deliverables

- code or api 

## Gains for the project

- helps the development for the token governance voting app

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: @troggy  / 75%
bounty reviewer: name / 15%

**Comment by troggy** [comment]
swapped workers @johannbarbie to @troggy as agreed on a General Tactical today

**Comment by troggy** [comment]
@cyan-one @johannbarbie 
IPFS use CID to reference uploaded objects. When converted to hex string it produces value like `0x122030239522d3f23d0c33df6a930164911b3da6d0b32ec65c119f735e94ccf5b812` which is 34 bytes and thus doesn't fit into contract. 

Should I cut metadata from CID (not great! could break in future) or should we increase make `hash` field in contract to be `bytes` instead?

**Comment by troggy** [comment]
decided to go with cutting the IPFS preamble as IPFS is sha256 only at the moment

**Comment by troggy** [comment]
via #277
