### ISSUE TITLE
add new token governance proposal feature

### ISSUE THREAD

**Issue by cyan-one** [leapdao/bridge-ui#272]
## Scope
- create a form that lets the user submit a new proposal  
- send a hash from the form to the smart contract
- display the stored ipfs link

## Deliverables
- code 
- token governance new proposal feature

## Gains for the project

- voting app for the network

## Roles
bounty gardener: @simonweniger / 10%
bounty worker: @simonweniger  / 75%
bounty reviewer: name / 15%

**Comment by simonweniger** [comment]
requesting resizing to **S**

**Comment by troggy** [comment]
via #269 and #270
