### ISSUE TITLE
Update "Governance" page to support Veto and Confidence votes

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#60]
# Bounty :

## Scope 
Stakeholders should be able to see pending governance proposals and veto them.
Related: https://github.com/leapdao/leap-contracts/issues/66
create a user interface (ideally in bridge) with the following abilities:

- list ongoing confidence votes
- display details (description, quorum, votes, deadline) for proposals
- display details (quorum, votes, deadline) for confidence votes
- allow to add confidence vote by paying stake
details
https://docs.google.com/document/d/1fC7YFgJB2QQbqbyJuU1AVqleLQPf6hEp0qNgj9-L_dM

## Deliverables
- Userinterface

## Gain for the project
- Ability to govern chain updates.

## Roles: 
bounty gardener: @johannbarbie / 10%
bounty worker: open / 80%
bounty reviewer: open / 10%

**Comment by johannbarbie** [comment]
governance beyond MinGov requires redesign.
