### ISSUE TITLE
Status page: get network node list from the connected node

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#86]
Currently, node list is hardcoded on the status page. Let's get it from the connected node to avoid redundancy

**Comment by troggy** [comment]
since #90 the set of node is specified per-network which is better (yet technically is still hardcoding)

**Comment by johannbarbie** [comment]
i'm not sure about this one. i might want to run a validator, but not expose it on the internet. why should we try to read the status from all of them?

**Comment by troggy** [comment]
you are right
