### ISSUE TITLE
Show when it is the last chance to exit safely

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#89]
Exits take time. In case governance proposal upgrades ExitHandler contract in a way which messes with the exits, it may be too late to exit even if proposal is not applied yet. Like this:

Timeline:
```
 <proposal created>-------------------------------<proposal applied>
                            <exit started>-------------------------------<exit finalized>
```

So we should display not only the time proposal becomes effective, but also the time left for safe exit. Safe exit = exit which will be finalized before the ExitHandler upgrade proposal applied.
This should consider the fact that it may take different time for different UTXOs to exit due to Plasma setup, somewhere in interval `[exitDuration, exitDuration × 2]` ([ref](https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L318)) where `exitDuration` should be read from the ExitHandler contract.

### Scope
- on a Governance page for each ExitHandler upgrade proposal show how much time remains for initiating safe exit
- distinguish between different states (e.g. with color coding and easy to understand text hint):
   - safe —  any exit will be finalized before ExitHandler upgrade proposal is applied (proposal applies after `exitDuration × 2` seconds).
   - may not be safe — some exits MAY be finalized after ExitHandler upgrade proposal is applied (proposal applies in `[exitDuration, exitDuration × 2]`)
   - not safe — any exit will be finalized after ExitHandler upgrade proposal is applied (proposal applies in less then `exitDuration` seconds)

Here `not safe` means that, depending on the nature of the ExitHandler upgrade, new contract logic MAY be used in the contract at the exit finalization time and thus potentially mess the exit. Probably `not safe` is a too strong wording here 🤔

### Bounty setup

Size: XS as per [bounty policy](https://app.glassfrog.com/policies/10912780)

gardener: @troggy / 10% — 20 DAI
worker: ___ / 80% — 160 DAI
reviewer: __ / 10% —20 DAI

**Comment by eswarasai** [comment]
@troggy -- I'm looking to get started with LeapDAO bounties. Is this something that I can pick up first and contribute to the project? Thanks :)

**Comment by troggy** [comment]
@eswarasai 👋

you are very welcome :). 
The best if you can tackle any bounty from Todo column [here](https://waffle.io/leapdao/leap-node?milestone=%E2%9A%97%200.7%20Alembic). This is our ongoing sprint and the most currently wanted things :) However, it may be challenging to start with, so feel free to pick any issue with [bounty](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aleapdao+label%3Abounty+no%3Aassignee) or [billable](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aleapdao+label%3Abillable+no%3Aassignee+) tag which is not yet assigned. Including this one. Billable issues are paid by a time spend (50 DAI/hour).

I've updated the description for this bounty according to reality, take a look if it makes sense.

If you feel like, [join our slack](https://docs.google.com/forms/d/e/1FAIpQLSd8_wDGDAi__HvfYEWNK_bvJzIkxwHHRVL6AFEfJewBd2Vn9A/viewform) — most of the action happens there, you may get faster response to your questions and get to know how we work. We have some good vibes over there 😎

**Comment by johannbarbie** [comment]
Won't it be confusing for people to see "not safe", they will assume that the upgrade is not safe, because they don't understand the priority queue of plasma.

**Comment by troggy** [comment]
yes, thought about this as well. Any ideas?

**Comment by johannbarbie** [comment]
mh, this has so many aspects:
- users will probably use the bridge-ui the least out of all the plApps.
- current setup is temporary, later distributed governance will do upgardes.

maybe i would just reduce the governance time by the maximum amount of exit duration. then we would have the following states:
- Applies in x (t < governance duration && t > max exit duration) days
- Pending for execution (t <= max exit duration) 
- completed/canceled

**Comment by troggy** [comment]
old and rusty
