### ISSUE TITLE
I got a Runtime Error

### ISSUE THREAD

**Issue by securekim** [leapdao/bridge-ui#94]
I got a Runtime Error, Please Help me.

brokim@anonymous:~/workspace/leapdao/bridge-ui$ yarn start
yarn run v1.10.1
$ ./node_modules/.bin/webpack-dev-server --config webpack.config.dev.js
Starting type checking service...
Using 1 worker with 2048MB memory limit
ℹ ｢wds｣: Project is running at http://localhost:1234/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
Type checking in progress...
⚠ ｢wdm｣: Hash: 535be0743da2710de64c
Version: webpack 4.27.1
Time: 35902ms
Built at: 2019. 01. 07. 오전 12:57:32
                               Asset        Size  Chunks             Chunk Names
3f99887f903cf946744f9da9a982a961.png    14.7 KiB          [emitted]  
5af1ec187d63930a0998895a5df36b31.svg  1000 bytes          [emitted]  
7efbc71c1c0fb24892eb3df82f98cbce.png   833 bytes          [emitted]  
f5eac1518665bcf468ff23181ade4951.png    1.93 KiB          [emitted]  
       index.535be0743da2710de64c.js    11.7 MiB    main  [emitted]  main
                          index.html    1.49 KiB          [emitted]  
Entrypoint main = index.535be0743da2710de64c.js
[0] multi (webpack)-dev-server/client?http://localhost:1234 ./src/index.tsx 40 bytes {main} [built]
[./node_modules/antd/dist/antd.min.css] 455 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/mobx-react/index.module.js] 48.7 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
[./node_modules/react-router/es/index.js] 723 bytes {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:1234] (webpack)-dev-server/client?http://localhost:1234 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/index.tsx] 4.14 KiB {main} [built]
    + 1599 hidden modules

WARNING in EnvironmentPlugin - CONFIG environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - NETWORK_ID environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - PLASMA_NODE environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
Child html-webpack-plugin for "index.html":
                                   Asset       Size  Chunks             Chunk Names
    3f99887f903cf946744f9da9a982a961.png   14.7 KiB          [emitted]  
    7efbc71c1c0fb24892eb3df82f98cbce.png  833 bytes          [emitted]  
    f5eac1518665bcf468ff23181ade4951.png   1.93 KiB          [emitted]  
     + 1 hidden asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 2.27 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
    [./src/apple-touch-icon.png] 82 bytes {0} [built]
    [./src/config sync recursive ^\.\/.*\/config\.json$] ./src/config sync ^\.\/.*\/config\.json$ 186 bytes {0} [optional] [built]
    [./src/config/env.js] 21 bytes {0} [not cacheable] [built]
    [./src/config/index.ts] 703 bytes {0} [built]
    [./src/config/testnet/config.json] 377 bytes {0} [optional] [built]
    [./src/favicon-16x16.png] 82 bytes {0} [built]
    [./src/favicon-32x32.png] 82 bytes {0} [built]
ℹ ｢wdm｣: Compiled with warnings.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types.d.ts(1,10):
TS2305: Module '"../@types/bn.js"' has no exported member 'BigNumber'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types.d.ts(1,27):
TS2497: Module '"/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/bn.js/index"' resolves to a non-module entity and cannot be imported using this construct.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/stores/contractStore.ts(55,7):
TS2322: Type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").Contract' is not assignable to type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/contract").default'.
  Types of property 'methods' are incompatible.
    Type '{ [fnName: string]: (...args: any[]) => import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionObject<any>; }' is not assignable to type '{ [fnName: string]: (...args: any[]) => import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/types").TransactionObject<any>; }'.
      Index signatures are incompatible.
        Type '(...args: any[]) => import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionObject<any>' is not assignable to type '(...args: any[]) => import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/types").TransactionObject<any>'.
          Type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionObject<any>' is not assignable to type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/types").TransactionObject<any>'.
            Types of property 'send' are incompatible.
              Type '(tx?: import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").Tx) => import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").PromiEvent<any>' is not assignable to type '(tx?: import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/types").Tx) => import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/promiEvent").default<any>'.
                Type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").PromiEvent<any>' is not assignable to type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/promiEvent").default<any>'.
                  Types of property 'once' are incompatible.
                    Type '{ (type: "transactionHash", handler: (receipt: string) => void): import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").PromiEvent<any>; (type: "receipt", handler: (receipt: import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionReceipt) => void): import("/home/brok...' is not assignable to type '{ (type: "transactionHash", handler: (receipt: string) => void): import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/promiEvent").default<any>; (type: "receipt", handler: (receipt: import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/types").TransactionReceipt) => void): im...'.
                      Types of parameters 'type' and 'type' are incompatible.
                        Type '"receipt"' is not assignable to type '"transactionHash"'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/stores/contractStore.ts(62,7):
TS2322: Type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").Contract' is not assignable to type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/contract").default'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/stores/contractStore.ts(68,5):
TS2322: Type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").Contract' is not assignable to type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/eth/contract").default'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/stores/governanceContract.ts(8,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/stores/token.ts(217,5):
TS2322: Type 'Promise<{ futureReceipt: PromiEvent<TransactionReceipt>; }>' is not assignable to type 'Promise<InflightTxReceipt>'.
  Type '{ futureReceipt: PromiEvent<TransactionReceipt>; }' is not assignable to type 'InflightTxReceipt'.
    Types of property 'futureReceipt' are incompatible.
      Type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").PromiEvent<import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionReceipt>' is not assignable to type 'import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/promiEvent").default<import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionReceipt>'.
        Types of property 'once' are incompatible.
          Type '{ (type: "transactionHash", handler: (receipt: string) => void): import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").PromiEvent<import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionReceipt>; (type: "receipt", handler: (receipt: import("/home/brokim/workspace/le...' is not assignable to type '{ (type: "transactionHash", handler: (receipt: string) => void): import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/@types/web3/promiEvent").default<import("/home/brokim/workspace/leapdao/bridge-ui/node_modules/web3/types").TransactionReceipt>; (type: "receipt", handler: (receipt: import("/home/brokim/wor...'.
            Types of parameters 'type' and 'type' are incompatible.
              Type '"receipt"' is not assignable to type '"transactionHash"'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/bridge.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/exitHandler.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/operator.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/proxy.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
Version: typescript 3.2.2

**Comment by troggy** [comment]
@securekim there were changes to typedefs recently. Could it be that your node_modules are not up to date?

I would recommend trying:
```
rm -rf node_modules
yarn
yarn start
```

**Comment by securekim** [comment]
Thank you for your answer.
Is it need pre-condition ?
Error message is changed, But it is exist yet.

brokim@anonymous:~/workspace/leapdao/bridge-ui$ yarn start
yarn run v1.10.1
$ ./node_modules/.bin/webpack-dev-server --config webpack.config.dev.js
Starting type checking service...
Using 1 worker with 2048MB memory limit
ℹ ｢wds｣: Project is running at http://localhost:1234/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
Type checking in progress...
⚠ ｢wdm｣: Hash: 940c1b542cff8a9b89c8
Version: webpack 4.27.1
Time: 20003ms
Built at: 2019. 01. 10. 오전 12:32:27
                               Asset        Size  Chunks             Chunk Names
3f99887f903cf946744f9da9a982a961.png    14.7 KiB          [emitted]  
5af1ec187d63930a0998895a5df36b31.svg  1000 bytes          [emitted]  
7efbc71c1c0fb24892eb3df82f98cbce.png   833 bytes          [emitted]  
f5eac1518665bcf468ff23181ade4951.png    1.93 KiB          [emitted]  
       index.940c1b542cff8a9b89c8.js    11.6 MiB    main  [emitted]  main
                          index.html    1.49 KiB          [emitted]  
Entrypoint main = index.940c1b542cff8a9b89c8.js
[0] multi (webpack)-dev-server/client?http://localhost:1234 ./src/index.tsx 40 bytes {main} [built]
[./node_modules/antd/dist/antd.min.css] 455 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/mobx-react/index.module.js] 48.7 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
[./node_modules/react-router/es/index.js] 723 bytes {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:1234] (webpack)-dev-server/client?http://localhost:1234 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/index.tsx] 4.14 KiB {main} [built]
    + 1582 hidden modules

WARNING in EnvironmentPlugin - CONFIG environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - NETWORK_ID environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - PLASMA_NODE environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
Child html-webpack-plugin for "index.html":
                                   Asset       Size  Chunks             Chunk Names
    3f99887f903cf946744f9da9a982a961.png   14.7 KiB          [emitted]  
    7efbc71c1c0fb24892eb3df82f98cbce.png  833 bytes          [emitted]  
    f5eac1518665bcf468ff23181ade4951.png   1.93 KiB          [emitted]  
     + 1 hidden asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 2.27 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
    [./src/apple-touch-icon.png] 82 bytes {0} [built]
    [./src/config sync recursive ^\.\/.*\/config\.json$] ./src/config sync ^\.\/.*\/config\.json$ 186 bytes {0} [optional] [built]
    [./src/config/env.js] 21 bytes {0} [not cacheable] [built]
    [./src/config/index.ts] 703 bytes {0} [built]
    [./src/config/testnet/config.json] 377 bytes {0} [optional] [built]
    [./src/favicon-16x16.png] 82 bytes {0} [built]
    [./src/favicon-32x32.png] 82 bytes {0} [built]
ℹ ｢wdm｣: Compiled with warnings.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/stores/governanceContract.ts(8,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/bridge.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/exitHandler.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/operator.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
ERROR in /home/brokim/workspace/leapdao/bridge-ui/src/utils/abis/proxy.ts(1,31):
TS2307: Cannot find module 'web3/Eth/ABI'.
Version: typescript 3.2.2
Time: 23075ms

**Comment by troggy** [comment]
> TS2307: Cannot find module 'web3/Eth/ABI'.

🤔looks like `@types/web3` module wasn't installed while it should be. 

Is this working for you `cat ./node_modules/@types/web3/package.json` ?

**Comment by securekim** [comment]
Yes, it is working. 
I reinstalled web3, But bug is still alive.
~/workspace/leapdao/bridge-ui$ cat ./node_modules/@types/web3/package.json
{
    "name": "@types/web3",
    "version": "1.0.12",
    "description": "TypeScript definitions for web3",
    "license": "MIT",
    "contributors": [
    ...
    ],
    "main": "",
    "types": "",
    "repository": {
        "type": "git",
        "url": "https://github.com/DefinitelyTyped/DefinitelyTyped.git"
    },
    "scripts": {},
    "dependencies": {
        "@types/bn.js": "*",
        "@types/underscore": "*"
    },
    "typesPublisherContentHash": "8799e948199590aa15af42599173847847b1ae761776b84a735e55df0bb2578b",
    "typeScriptVersion": "2.4"

**Comment by securekim** [comment]
What is these environments ? There are warnings when I build it.
```

WARNING in EnvironmentPlugin - CONFIG environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - NETWORK_ID environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - PLASMA_NODE environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
```

**Comment by securekim** [comment]
OMG... someone reference web3/**E**th and 
other guys reference web3/**e**th. 
Why ?

**Comment by securekim** [comment]
@troggy  I made a patch.. and there is no error anymore... But is it right way ? 
```

diff --git a/src/stores/governanceContract.ts b/src/stores/governanceContract.ts
index 1ee7f29..3ee5698 100644
--- a/src/stores/governanceContract.ts
+++ b/src/stores/governanceContract.ts
@@ -5,7 +5,7 @@
  * found in the LICENSE file in the root directory of this source tree.
  */
 import Web3Store from './web3';
-import { ABIDefinition } from 'web3/Eth/ABI';
+import { ABIDefinition } from 'web3-eth-abi';
 import { range } from '../utils';
 import { 
   governance as governanceAbi,
diff --git a/src/utils/abis/bridge.ts b/src/utils/abis/bridge.ts
index 3c6dba9..b04c785 100644
--- a/src/utils/abis/bridge.ts
+++ b/src/utils/abis/bridge.ts
@@ -1,4 +1,4 @@
-import { ABIDefinition } from 'web3/Eth/ABI';
+import { ABIDefinition } from 'web3-eth-abi';
 
 export default [
   {
diff --git a/src/utils/abis/exitHandler.ts b/src/utils/abis/exitHandler.ts
index 85181d7..30a25fa 100644
--- a/src/utils/abis/exitHandler.ts
+++ b/src/utils/abis/exitHandler.ts
@@ -1,4 +1,4 @@
-import { ABIDefinition } from 'web3/Eth/ABI';
+import { ABIDefinition } from 'web3-eth-abi';
 
 export default [
   {
diff --git a/src/utils/abis/poaOperator.ts b/src/utils/abis/poaOperator.ts
index 70aeab8..0bff456 100644
--- a/src/utils/abis/poaOperator.ts
+++ b/src/utils/abis/poaOperator.ts
@@ -1,4 +1,4 @@
-import { ABIDefinition } from 'web3/Eth/ABI';
+import { ABIDefinition } from 'web3-eth-abi';
 
 export default [
   {
diff --git a/src/utils/abis/posOperator.ts b/src/utils/abis/posOperator.ts
index d428192..3acc1d4 100644
--- a/src/utils/abis/posOperator.ts
+++ b/src/utils/abis/posOperator.ts
@@ -1,4 +1,4 @@
-import { ABIDefinition } from 'web3/Eth/ABI';
+import { ABIDefinition } from 'web3-eth-abi';
 
 export default [
   {
diff --git a/src/utils/abis/proxy.ts b/src/utils/abis/proxy.ts
index 616e15f..6976a10 100644
--- a/src/utils/abis/proxy.ts
+++ b/src/utils/abis/proxy.ts
@@ -1,4 +1,4 @@
-import { ABIDefinition } from 'web3/Eth/ABI';
+import { ABIDefinition } from 'web3-eth-abi';
 
 export default [
   {

```
